
import java.awt.Color;
import java.io.BufferedReader;
import java.io.FileReader;
import java.util.Formatter;
import java.util.Scanner;
import javax.swing.JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author berke
 */
public class AddBaitFrame extends javax.swing.JFrame {

    boolean colorChooserBoolean = true;
    static int size = 250;
    static float floatingRange = 25f;
    static Color color1 = Color.RED;
    static Color color2 = Color.YELLOW;
    
    /**
     * Creates new form AddBaitFrame
     */
    public AddBaitFrame() {
        
        initComponents();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);	
        confirmationDialog.setSize(320, 180);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        confirmationDialog = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        noButton = new javax.swing.JButton();
        yesButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        sizeLabel = new javax.swing.JLabel();
        sizeSlider = new javax.swing.JSlider(10,600,250);
        baitColorChooser = new javax.swing.JColorChooser();
        colorChooserLabel = new javax.swing.JLabel();
        floatingRangeSlider = new javax.swing.JSlider();
        jLabel4 = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        sizeIndicator = new javax.swing.JLabel();
        rangeIndicator = new javax.swing.JLabel();
        baitColorChooser2 = new javax.swing.JColorChooser();
        jLabel1 = new javax.swing.JLabel();

        confirmationDialog.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setText("Create Fish Instance from Template now ?");

        noButton.setText("No");
        noButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noButtonActionPerformed(evt);
            }
        });

        yesButton.setText("Yes");
        yesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesButtonActionPerformed(evt);
            }
        });

        jLabel10.setText("Template Saved!");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(yesButton)
                        .addGap(68, 68, 68)
                        .addComponent(noButton))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9))))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yesButton)
                    .addComponent(noButton))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        confirmationDialog.getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 170));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sizeLabel.setText("Size");

        sizeSlider.setMajorTickSpacing(20);
        sizeSlider.setMinorTickSpacing(5);
        sizeSlider.setPaintTicks(true);
        sizeSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sizeSliderStateChanged(evt);
            }
        });

        baitColorChooser.setPreviewPanel(new javax.swing.JPanel());
        baitColorChooser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                baitColorChooserMouseClicked(evt);
            }
        });

        colorChooserLabel.setText("Color_1");

        floatingRangeSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                floatingRangeSliderStateChanged(evt);
            }
        });

        jLabel4.setText("Floating Range");

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        sizeIndicator.setText("Size");

        rangeIndicator.setText("Range");

        baitColorChooser2.setPreviewPanel(new javax.swing.JPanel());

        jLabel1.setText("Color 2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(sizeLabel)
                                .addGap(29, 29, 29))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(floatingRangeSlider, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                            .addComponent(sizeSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sizeIndicator)
                            .addComponent(rangeIndicator)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(colorChooserLabel)
                                    .addGap(18, 18, 18)
                                    .addComponent(baitColorChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(baitColorChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(65, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sizeSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sizeLabel)
                    .addComponent(sizeIndicator))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(floatingRangeSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(rangeIndicator))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(colorChooserLabel)
                    .addComponent(baitColorChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(baitColorChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sizeSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sizeSliderStateChanged
        // TODO add your handling code here:
        sizeIndicator.setText(String.valueOf(sizeSlider.getValue()));
        size = sizeSlider.getValue();
    }//GEN-LAST:event_sizeSliderStateChanged

    private void floatingRangeSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_floatingRangeSliderStateChanged
        // TODO add your handling code here:
        floatingRange = floatingRangeSlider.getValue();
        rangeIndicator.setText(String.valueOf(floatingRange));

    }//GEN-LAST:event_floatingRangeSliderStateChanged

    private void baitColorChooserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_baitColorChooserMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_baitColorChooserMouseClicked

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        color1 = baitColorChooser.getColor();
        color2 = baitColorChooser2.getColor();
        writeToFile();
        confirmationDialog.setVisible(true);
    }//GEN-LAST:event_saveButtonActionPerformed

    private void noButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noButtonActionPerformed
        this.setVisible(false);
        confirmationDialog.setVisible(false);
    }//GEN-LAST:event_noButtonActionPerformed

    private void yesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesButtonActionPerformed
        // TODO add your handling code here:
        confirmationDialog.setVisible(false);
        this.setVisible(false);
        EnviromentPanel.generateParameteredBait(size, color1, color2, floatingRange);
    }//GEN-LAST:event_yesButtonActionPerformed

     private static void readFromFile(){
        BufferedReader br = null;
        Scanner sc = null;
        int r1,g1,b1,r2,g2,b2;
        try {
            sc = new Scanner(new FileReader("baitConfig.txt"));
          
       
            while(!"Bait".equals(sc.next())){
                sc.next();
            }
            sc.next();
            size = sc.nextInt();
            sc.next();
            floatingRange = sc.nextFloat();
            sc.next();
            r1 = sc.nextInt();
            sc.next();
            g1 = sc.nextInt();
            sc.next();
            b1 = sc.nextInt();
            sc.next();
            r2 = sc.nextInt();
            sc.next();
            g2 = sc.nextInt();
            sc.next();
            b2 = sc.nextInt();
            color1 = new Color(r1,g1,b1);
            color2 = new Color(r2,g2,b2);
            
        } catch (Exception e) {
            
        }
        
    }
    
    public static void writeToFile(){
        try {
            Formatter formatterX = new Formatter("baitConfig.txt");
            int r1,r2,g1,g2,b1,b2;
            r1 = color1.getRed();
            g1 = color1.getGreen();
            b1 = color1.getBlue();
            r2 = color2.getRed();
            g2 = color2.getGreen();
            b2 = color2.getBlue();
            
            formatterX.format("%s", "Bait \n");
            formatterX.format("%s", "Bait_size ");
            formatterX.format("%s\n", size);
            formatterX.format("%s", "Bait_floatingRange ");
            formatterX.format("%s\n", floatingRange);
            formatterX.format("%s", "Bait_color1_R ");
            formatterX.format("%s\n", r1);
            formatterX.format("%s", "Bait_color1_G ");
            formatterX.format("%s\n", g1);
            formatterX.format("%s", "Bait_color1_b ");
            formatterX.format("%s\n", b1);
            formatterX.format("%s", "Bait_color2_R ");
            formatterX.format("%s\n", r2);
            formatterX.format("%s", "Bait_color2_G ");
            formatterX.format("%s\n", g2);
            formatterX.format("%s", "Bait_color2_b ");
            formatterX.format("%s\n", b2);
            
            
            formatterX.close();
            
        
            readFromFile();
        
        } catch (Exception e) {
            
        }
        
        
    
        
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddBaitFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddBaitFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddBaitFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddBaitFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddBaitFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JColorChooser baitColorChooser;
    private javax.swing.JColorChooser baitColorChooser2;
    private javax.swing.JLabel colorChooserLabel;
    private javax.swing.JDialog confirmationDialog;
    private javax.swing.JSlider floatingRangeSlider;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton noButton;
    private javax.swing.JLabel rangeIndicator;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel sizeIndicator;
    private javax.swing.JLabel sizeLabel;
    private javax.swing.JSlider sizeSlider;
    private javax.swing.JButton yesButton;
    // End of variables declaration//GEN-END:variables
}
